# Generated by Django 5.2.7 on 2025-10-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LibraryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.library')),
            ],
            options={
                'unique_together': {('library', 'book')},
            },
        ),
    ]
